### ISSUE TITLE
README assumptions and structure

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#109]
The code here is a bit obscure for me: https://github.com/etiennebacher/altdoc/blob/main/R/utils-rmd.R#L3

What assumptions are we making about the README? I imagine that we want to support 3 types of readme: .md, .Rmd, and .qmd.

The default folders in which images are stored probably differ.

Where should users store static images if they have any?

**Comment by etiennebacher** [comment]
The README is a special case because it already has to be rendered to .md to appear on Github/Gitlab so we don't have to render it ourselves. This is why I hardcoded the filename `"README.md"` in the code linked.

> Where should users store static images if they have any?

Many places possible: in issues (I think you did that at some point?), in `man` (like [withr](https://github.com/r-lib/withr/tree/main/man/figures)), in `inst`...

A way to do it is:

* images that are accessed via URLs don't need to be changed since the URLs will still work as before
* images that have a path in the repo should be copied to `docs/README_assets` and the path should be updated every time `render_docs()` is called

I think the code linked above already does that and it works fine for `withr`.

What do you think?
