### ISSUE TITLE
Docs using R and Python?

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/altdoc#194]
IIRC, one of the benefits of using quarto is to make docs where one can mix R and python (without going through `reticulate`). Didn't you have something like that in mind @vincentarelbundock ?

If so, that would be a cool feature to differentiate from pkgdown and it would be nice to have a demo of this somewhere in the docs or in another repo.

**Comment by vincentarelbundock** [comment]
Yep, it's called "tabset" and they have examples on the Quarto website.

The polars user guide gas a similar thing for rust and pythonso it should be possible in mkdocs as well.

**Comment by vincentarelbundock** [comment]
Although, I will say that I think this falls in the kinds of documentation that we can mention but don't have to illustrate. (That was your argument for keeping the customization vignette simple, I think.)

**Comment by eitsupi** [comment]
> IIRC, one of the benefits of using quarto is to make docs where one can mix R and python (without going through `reticulate`).

What does this mean?
We cannot use knitr and jupyter in one file, because Quarto only allows one engine in one file.
We need reticulate when evaluating Python code blocks using the knitr engine and we cannot use code blocks in more than one language within Jupyter.
In other words, reticulate is required to use R and Python simultaneously in a single file.

It is possible to render each page with knitr and jupyter respectively.

**Comment by etiennebacher** [comment]
I never rendered quarto docs having python and R code together so I thought it would be seamless. In any case, there's probably no need to talk about running python code in the docs here
