### ISSUE TITLE
Simplify vignettes

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#43]
I'm wondering if we could simplify the vignette code by:

1. Copying the whole content of `vignettes/` over to `docs/articles/`. This would preserve relative links and allow us to remove the figures modification code, which relies on tricky regexes. https://github.com/etiennebacher/altdoc/blob/main/R/vignettes.R#L39
2. Use the `output_format` argument in `rmarkdown::render` to obviate the need to hack the YAML: https://github.com/etiennebacher/altdoc/blob/main/R/vignettes.R#L54

**Comment by etiennebacher** [comment]
Yes, there are probably ways to simplify the code of `altdoc` in many ways. For vignettes, I feel like it's just a list of hacks that I put together as I found special cases. People write vignettes in so many ways that it's hard to cover everything. 

However, `altdoc` is pretty low on my todo list for now (basically it works for my packages that use it and I don't see a large demand for this). If you want to do some PR, I'd be happy to review (not in the next couple of weeks because holidays are coming) but I guess you're also quite busy, especially now that you started the Python variants of your packages ;)

**Comment by vincentarelbundock** [comment]
cool cool. Yeah, I just started writing some functions to document a package of mine and realized I was replicating a bunch of your functionality. So it probably makes more sense for me to work to improve `altdoc` to get it where I need to be.

In the end, it would be fun for `polars` to use `altdoc` directly, perhaps with some "hook" mechanism to populate the table of contents.
