### ISSUE TITLE
Evaluating examples errors because of `@examplesIf`

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/altdoc#45]
Evaluating examples should take into account the roxygen tag `@examplesIf`. Problem: `Rd2HTML()` doesn't take those into account:
``` r
  temp_rd <- tempfile(fileext = ".Rd")
  cat('
\\name{adjust}
\\title{Adjust data for the effect of other variable(s)}
\\examples{
\\dontshow{if (require("bayestestR", quietly = TRUE))}
adjusted_all = adjust(attitude)
}',
      file = temp_rd
  )
  
  tools::Rd2HTML(temp_rd, standalone = FALSE)
#> <h2 id='adjust'>Adjust data for the effect of other variable(s)</h2>
#> 
#> <h3>Examples</h3>
#> 
#> <pre><code class='language-R'>
#> adjusted_all = adjust(attitude)
#> </code></pre>
```

**Comment by vincentarelbundock** [comment]
This should be fixed now.

Currently, we run `grepl("dontrun|dontest", x)` where `x` is the examples section of a man page. If this returns `TRUE`, then we do not render the examples section at all.

This is a bit aggressive, because in principle some parts of the examples could be wrapped and others not (I think), but it works for now. And parsing the examples section to figure out what is `\dontrun{}` or not would be very tricky.
