### ISSUE TITLE
Test against `polars`

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#59]
This is a note to self with a reminder that we should test big PRs against the `polars` website build when possible. Instructions from:

https://github.com/etiennebacher/altdoc/pull/55#issuecomment-1798367443

> You need to have a fork of `polars` (not necessarily up to date), then in the terminal: 
> ```bash
> Rscript -e 'altdoc::update_docs(custom_reference = "docs/make-docs.R")'
> cd docs && python3 -m mkdocs serve
> ```
> This should provide a link to the preview in the terminal. 
> 
> You might need to build `polars` for this to work, and therefore have a Rust installation. I'll check anyway before each `altdoc` release.

**Comment by rempsyc** [comment]
I'm curious if we found exactly what breaks `polars`

**Comment by vincentarelbundock** [comment]
FWIW, I'm working on a big refactor with immutable files now, so this will have to be tested later anyway. There's no point in testing the current version right now, because a lot of the internals might change.

**Comment by eitsupi** [comment]
By the way, the release version (v0.Y.Z) of R polars can be built without Rust (when set `NOT_CRAN="true"`), so if you only want to try out the website, it may be easier to do it on a release version commit.

**Comment by etiennebacher** [comment]
I'm working on adapting `polars` to work with the new version of `altdoc`. Using a pre-processing script to organize the "Reference" page looks like it works fine but the problem is the time needed to render the man pages. We have a bit less than 600 man pages to render and each of these call a Quarto process, which is very slow (takes more than 35min without parallel).

I opened https://github.com/pola-rs/r-polars/pull/540 to explore potential bugs, let's see how long it takes with parallel rendering there

**Comment by vincentarelbundock** [comment]
Good (and bad) to know.

FWIW, the `freeze` option works extremely well on my `marginaleffects` package, where building the site can take 15 minutes. It's almost instantaneous the second time we run it...

**Comment by etiennebacher** [comment]
I should try with `freeze` later then. `polars` is also an extreme example, I don't think there are many packages with more than 100 man pages, let alone 500+ 😄 If the parallel rendering in GHA could divide the total time by 4, that would be nice (currently the docs workflow of `polars` takes around 5min when it doesn't need to recompile the Rust part)

**Comment by vincentarelbundock** [comment]
I think we can also commit `altdoc/freeze.rds`, and it would speed up GHA too.

**Comment by etiennebacher** [comment]
I really dislike having `freeze = TRUE` in GHA, to me this option should only be used locally for convenience

**Comment by vincentarelbundock** [comment]
Fair enough.

What's the use case you have in mind where this may fail? Since we're hashing the `.qmd` files, the only problem I see is if we change a static file outside of `.qmd`. Is that what you worry about? My guess is that won't happen in `polars`, but maybe I'm missing something.

**Comment by etiennebacher** [comment]
When we update rust-polars, the code and the docs of the R functions doesn't necessarily change but their behavior might, so if we use `freeze = TRUE` then we don't see potential mistakes in the examples due to these background changes. Ideally these should be covered in unit tests, but there are so many functions in `polars` that for now we are far from 100% test coverage.

`freeze = TRUE` could be used in the future but for now I think it's too risky

**Comment by vincentarelbundock** [comment]
ooof, yes, obviously. Thanks.

**Comment by etiennebacher** [comment]
The CI now passes in https://github.com/pola-rs/r-polars/pull/540 but rendering the docs takes 17min, which is a lot compared to the current workflow.
